// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("AccountingCrossReferenceEntries")]
    public partial class AccountingCrossReferenceEntry 
    {
        [Required]
		[PrimaryKey]
        public Guid AccountingCrossReferenceEntryID { get; set; }
        [Required]
        public Guid AccountID { get; set; }
        [Required]
        public string Type { get; set; }
        [Required]
        public string Segment1 { get; set; }
        [Required]
        public string Segment2 { get; set; }
        [Required]
        public string Segment3 { get; set; }
        [Required]
        public string Segment4 { get; set; }
        [Required]
        public string Segment5 { get; set; }
    }

}
#pragma warning restore 1591
