// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("CloudTicketSyncBatches")]
    public partial class CloudTicketSyncBatch 
    {
        [Required]
		[PrimaryKey]
        public Guid CloudTicketSyncBatchID { get; set; }
        [Required]
        public DateTime BatchDate { get; set; }
        [Required]
        public bool IsPosted { get; set; }
        [Required]
        public bool IsVoided { get; set; }
        [Required]
        public DateTimeOffset SyncDateTime { get; set; }
        [Required]
        public Guid CloudDailyCloseID { get; set; }
        [Required]
        public Guid CloudDepartmentID { get; set; }
        [Required]
        public string CloudDepartmentName { get; set; }
        [Required]
        public string CloudDepartmentUrl { get; set; }
        [Required]
        public Guid ConsoleDepartmentID { get; set; }
        [Required]
        public string ConsoleDepartmentName { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
