// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("ConditionReservationDayOfWeekAndTimeRange")]
    public partial class ConditionReservationDayOfWeekAndTimeRange 
    {
        [Required]
		[PrimaryKey]
        public Guid Id { get; set; }
        [Required]
        public int FromDay { get; set; }
        [Required]
        public int FromTime_Hour { get; set; }
        [Required]
        public int FromTime_Minute { get; set; }
        [Required]
        public int FromTime_Second { get; set; }
        [Required]
        public int State { get; set; }
        [Required]
        public int ToDay { get; set; }
        [Required]
        public int ToTime_Hour { get; set; }
        [Required]
        public int ToTime_Minute { get; set; }
        [Required]
        public int ToTime_Second { get; set; }
    }

}
#pragma warning restore 1591
