// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("DailySyncJobs")]
    public partial class DailySyncJob 
    {
        [Required]
        public Guid DailyCloseID { get; set; }
        [Required]
        public Guid TrackingID { get; set; }
        [Required]
        public string BackgroundJobID { get; set; }
        public string Status { get; set; }
        public string Data { get; set; }
        [Required]
        public DateTimeOffset Modified { get; set; }
    }

}
#pragma warning restore 1591
