// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("EventLog")]
    public partial class EventLog 
    {
        [Required]
		[PrimaryKey]
        public Guid EventID { get; set; }
        [Required]
        public DateTimeOffset EventTime { get; set; }
        [Required]
        public string EventType { get; set; }
        [Required]
        public string EventCategory { get; set; }
        [Required]
        public string EventSource { get; set; }
        [Required]
        public string Notes { get; set; }
        public Guid? ClubID { get; set; }
        public Guid? UserID { get; set; }
        public Guid? DepartmentID { get; set; }
        public Guid? RegisterID { get; set; }
        public string IPAddress { get; set; }
        public string TrackingID { get; set; }
        [Required]
        public string AuditLogin { get; set; }
        [Required]
        public string AuditHostName { get; set; }
    }

}
#pragma warning restore 1591
