// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("Jobs")]
    public partial class Job 
    {
        [Required]
		[PrimaryKey]
        public Guid JobID { get; set; }
        [Required]
        public Guid JobBatchID { get; set; }
        [Required]
        public string JobStatus { get; set; }
        public string Data { get; set; }
        public string HangfireBackgroundJobID { get; set; }
        public bool? CompletedSuccessfully { get; set; }
        public string ErrorMessage { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Queued { get; set; }
        public DateTimeOffset? Completed { get; set; }
    }

}
#pragma warning restore 1591
