// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("PhoneNumbers")]
    public partial class PhoneNumber 
    {
        [Required]
		[PrimaryKey]
        public Guid PhoneNumberID { get; set; }
        [Required]
        public int EntityID { get; set; }
        [Required]
        public Guid EntityRecordID { get; set; }
        [Required]
        public string PhoneNumberLabel { get; set; }
        [Alias("PhoneNumber")]
        [Required]
        public string _PhoneNumber { get; set; }
        public string PhoneExtension { get; set; }
        [Required]
        public bool IsPrimary { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
