// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("PlayerBookings")]
    public partial class PlayerBooking 
    {
        [Required]
        public int Order { get; set; }
        [Required]
        public decimal Rate { get; set; }
        [Required]
        public Guid Item_Id { get; set; }
        [Required]
        public Guid PlayerId { get; set; }
        [Required]
        public int PlayerTypeId { get; set; }
        [Required]
        public int State { get; set; }
        public string DisplayName { get; set; }
        [AutoIncrement]
		[PrimaryKey]
        public int Id { get; set; }
        [Required]
        public int BookedSlotId { get; set; }
        public Guid? LockId { get; set; }
        [Required]
        public bool IsDeleted { get; set; }
    }

}
#pragma warning restore 1591
