// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("ReportNodes")]
    public partial class ReportNode 
    {
        [Required]
		[PrimaryKey]
        public Guid ReportNodeID { get; set; }
        public Guid? ParentReportNodeID { get; set; }
        [Required]
        public string NodeType { get; set; }
        [Required]
        public int DisplayOrder { get; set; }
        [Required]
        public string Name { get; set; }
        public string VisibilityFlagsCSV { get; set; }
        public string ReportKey { get; set; }
    }

}
#pragma warning restore 1591
