// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("SlotTags")]
    public partial class SlotTag 
    {
        [AutoIncrement]
		[PrimaryKey]
        public long Id { get; set; }
        public string Label { get; set; }
        [Required]
        public int TagType { get; set; }
        public string Color { get; set; }
        public int? RestrictionType { get; set; }
        [Required]
        public string Discriminator { get; set; }
        public int? Tee_Id { get; set; }
    }

}
#pragma warning restore 1591
