// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("SlotSchedules")]
    public partial class SlotSchedule 
    {
        [AutoIncrement]
		[PrimaryKey]
        public int Id { get; set; }
        [Required]
        public DateTime EndDate { get; set; }
        [Required]
        public int EndTime_Hour { get; set; }
        [Required]
        public int EndTime_Minute { get; set; }
        [Required]
        public int EndTime_Second { get; set; }
        [Required]
        public bool Friday { get; set; }
        [Required]
        public bool Monday { get; set; }
        [Required]
        public bool Saturday { get; set; }
        [Required]
        public DateTime StartDate { get; set; }
        [Required]
        public int StartTime_Hour { get; set; }
        [Required]
        public int StartTime_Minute { get; set; }
        [Required]
        public int StartTime_Second { get; set; }
        [Required]
        public bool Sunday { get; set; }
        [Required]
        public bool Thursday { get; set; }
        [Required]
        public bool Tuesday { get; set; }
        [Required]
        public bool Wednesday { get; set; }
        [Required]
        public double IntervalMinutes { get; set; }
    }

}
#pragma warning restore 1591
