// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblActiveEdits")]
    public partial class tblActiveEdit 
    {
        [Required]
		[PrimaryKey]
        public Guid uidActiveEditID { get; set; }
        [Required]
        public string strComputerName { get; set; }
        [Required]
        public Guid uidOwnerID { get; set; }
        [Required]
        public Guid uidUserID { get; set; }
        [Required]
        public Guid uidObjectID { get; set; }
        [Required]
        public DateTime dtmDateTime { get; set; }
    }

}
#pragma warning restore 1591
