// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("tblAddresses")]
    public partial class tblAddress 
    {
        [Required]
		[PrimaryKey]
        public Guid uidAddressID { get; set; }
        [Required]
        public string strAddressLine1 { get; set; }
        [Required]
        public string strAddressLine2 { get; set; }
        [Required]
        public string strAddressLine3 { get; set; }
        [Required]
        public string strCity { get; set; }
        [Required]
        public Guid uidStateAndProvinceID { get; set; }
        [Required]
        public string strPostalCode { get; set; }
        [Required]
        public Guid uidCountryID { get; set; }
        [Required]
        public string strDayTimePhone { get; set; }
        [Required]
        public string strDayTimeExtension { get; set; }
        [Required]
        public string strNightTimePhone { get; set; }
        [Required]
        public string strNightTimeExtension { get; set; }
        [Required]
        public string strFaxNumber { get; set; }
        [Required]
        public string strMobilePhone { get; set; }
        public DateTime? dtmSeasonalBeginDate { get; set; }
        public DateTime? dtmSeasonalEndDate { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
