// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("tblBILog")]
    public partial class tblBILog 
    {
        [Required]
        public Guid uidLogID { get; set; }
        public DateTimeOffset? dtmRun { get; set; }
        public string strModule { get; set; }
        public string strValue { get; set; }
        public string strNotes { get; set; }
        public DateTimeOffset? dtmBeginTime { get; set; }
        public DateTimeOffset? dtmEndTime { get; set; }
        public DateTimeOffset? dtmRunTime { get; set; }
        public int? lngErrorNumber { get; set; }
        public int? lngErrorSeverity { get; set; }
        public int? lngErrorState { get; set; }
        public string strErrorProcedure { get; set; }
        public int? lngErrorLine { get; set; }
        public string strErrorMessage { get; set; }
    }

}
#pragma warning restore 1591
