// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblCC_Trans")]
    public partial class tblCC_Tran 
    {
        [Required]
		[PrimaryKey]
        public Guid uidCC_TranID { get; set; }
        [Required]
        public string strRequestType { get; set; }
        public string strMerchantNumber { get; set; }
        [Required]
        public string strMerchantPassword { get; set; }
        [Required]
        public string strCC_Name { get; set; }
        public string strCC_Number { get; set; }
        [Required]
        public string strCC_ExpirationDate { get; set; }
        [Required]
        public bool blnCardSwiped { get; set; }
        [Required]
        public decimal curAmountCharged { get; set; }
        [Required]
        public decimal curAddedTip { get; set; }
        [Required]
        public decimal curTotalTax { get; set; }
        [Required]
        public string strApprovalNumber { get; set; }
        [Required]
        public Guid uidDeptID { get; set; }
        [Required]
        public Guid uidTicketTranID { get; set; }
        [Required]
        public Guid uidTicketID { get; set; }
        [Required]
        public bool blnApproved { get; set; }
        public string strTranSequenceNumber { get; set; }
        [Required]
        public string strRetrievalNumber { get; set; }
        [Required]
        public string strErrorMessage { get; set; }
        [Required]
        public bool blnCardPresent { get; set; }
        [Required]
        public int lngMultiSequenceNumber { get; set; }
        [Required]
        public int lngMultiSequenceCount { get; set; }
        [Required]
        public string strAVS_Street { get; set; }
        [Required]
        public string strAVS_Zip { get; set; }
        [Required]
        public string strCardType { get; set; }
        [Required]
        public string strSessionID { get; set; }
        public string strResponse { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
