// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("tblCertCodes")]
    public partial class tblCertCode 
    {
        [Required]
		[PrimaryKey]
        public Guid uidCertCodeID { get; set; }
        [Required]
        public Guid uidSellableItemID { get; set; }
        [Required]
        public bool blnSystemCreatesNumber { get; set; }
        [Required]
        public bool blnAskForPurchaser { get; set; }
        [Required]
        public bool blnAskForReceiver { get; set; }
        [Required]
        public bool blnRequirePurchaser { get; set; }
        [Required]
        public bool blnRequireReciever { get; set; }
        [Required]
        public bool blnCertsExpire { get; set; }
        [Required]
        public int lngExpireOn { get; set; }
        [Required]
        public int lngExpireMonths { get; set; }
        public DateTimeOffset? dtmExpireDate { get; set; }
        [Required]
        public bool blnExpireOnZ { get; set; }
        [Required]
        public bool blnAllowChange { get; set; }
        [Required]
        public decimal curChangeLimit { get; set; }
        [Required]
        public bool blnIssueNewCertWhenUsed { get; set; }
        [Required]
        public bool blnUseOriginalExpirationDate { get; set; }
        [Required]
        public bool blnCreateNewCertWhenReturning { get; set; }
        [Required]
        public bool blnDeleteZeroDollarBalances { get; set; }
        [Required]
        public bool blnAllowReloadOfCert { get; set; }
        [Required]
        public bool blnUseOnCertainAcctCodes { get; set; }
        [Required]
        public bool blnAskForEachNumber { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
