// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblDailyCloses")]
    public partial class tblDailyClose 
    {
        [Required]
		[PrimaryKey]
        public Guid uidDailyCloseID { get; set; }
        [Required]
        public Guid uidDeptID { get; set; }
        [Required]
        public DateTime dtmZeeDate { get; set; }
        [Required]
        public string txtCloseNote { get; set; }
        [Required]
        public Guid uidCourseConditionID { get; set; }
        [Required]
        public Guid uidWeatherCodeID { get; set; }
        [Required]
        public int lngTemperatureLow { get; set; }
        [Required]
        public int lngTemperatureHigh { get; set; }
        [Required]
        public bool blnDayClosed { get; set; }
        [Required]
        public string strCloseComment { get; set; }
        [Required]
        public bool blnTransferredToAccting { get; set; }
    }

}
#pragma warning restore 1591
