// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("tblDepts")]
    public partial class tblDept 
    {
        [Required]
		[PrimaryKey]
        public Guid uidDeptID { get; set; }
        [Required]
        public string strName { get; set; }
        [Required]
        public bool blnFoodAndBeverage { get; set; }
        [Required]
        public bool blnRetail { get; set; }
        [Required]
        public Guid uidHomeClubID { get; set; }
        [Required]
        public string strNumber { get; set; }
        [Required]
        public bool blnAdmin { get; set; }
        public string strFriendlyName { get; set; }
        [Required]
        public decimal curCashDenomination1 { get; set; }
        [Required]
        public decimal curCashDenomination2 { get; set; }
        [Required]
        public decimal curCashDenomination3 { get; set; }
        [Required]
        public decimal curCashDenomination4 { get; set; }
        [Required]
        public decimal curCashDenomination5 { get; set; }
        [Required]
        public decimal curCashDenomination6 { get; set; }
        [Required]
        public decimal curCashDenomination7 { get; set; }
        [Required]
        public decimal curCashDenomination8 { get; set; }
        [Required]
        public decimal curCashDenomination9 { get; set; }
        [Required]
        public decimal curCashDenomination10 { get; set; }
        [Required]
        public decimal curCashDenomination11 { get; set; }
        [Required]
        public string strTimeZoneID { get; set; }
        public string strPostalCode { get; set; }
        [Required]
        public bool blnActive { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
