// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("tblEmpls")]
    public partial class tblEmpl 
    {
        [Required]
		[PrimaryKey]
        public Guid uidEmplID { get; set; }
        [Required]
        public Guid uidPersonID { get; set; }
        [Required]
        public string strPassword { get; set; }
        [Required]
        public bool blnPoolGrat { get; set; }
        [Required]
        public bool blnRequireClockIn { get; set; }
        [Required]
        public string strNumber { get; set; }
        [Required]
        public Guid uidZeeID { get; set; }
        [Required]
        public Guid uidHomeClubID { get; set; }
        [Required]
        public bool blnExternal { get; set; }
        [Required]
        public bool blnDeleted { get; set; }
        [Required]
        public bool blnRightHandedRegisters { get; set; }
        [Required]
        public string strSourceAccountingCompany { get; set; }
        [Required]
        public string strSourceAccountingKey { get; set; }
        [Required]
        public bool blnAllocateTips { get; set; }
        [Required]
        public bool blnRegisterUser { get; set; }
        [Required]
        public bool blnIBSAdminUser { get; set; }
        [Required]
        public string strPIN { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
