// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblInvTrans")]
    public partial class tblInvTran 
    {
        [Required]
		[PrimaryKey]
        public Guid uidInvTranID { get; set; }
        [Required]
        public Guid uidInvItemID { get; set; }
        [Required]
        public Guid uidTicketTranID { get; set; }
        [Required]
        public string strReference { get; set; }
        [Required]
        public decimal decCost { get; set; }
        [Required]
        public decimal lngQty { get; set; }
        [Required]
        public Guid uidVendorID { get; set; }
        [Required]
        public string strInvTranType { get; set; }
        [Required]
        public DateTimeOffset dtmTranDate { get; set; }
        [Required]
        public int lngInvSize { get; set; }
        [Required]
        public string strSizeLabel { get; set; }
        [Required]
        public bool blnPrinted { get; set; }
        [Required]
        public int lngPurchaseToSellConversion { get; set; }
        [Required]
        public Guid uidReceiptLogID { get; set; }
        [Required]
        public decimal curPrice { get; set; }
        [Required]
        public decimal decAvgCost { get; set; }
        [Required]
        public Guid uidEmplID { get; set; }
        [Required]
        public Guid uidSoItemID { get; set; }
        [Required]
        public string strPO { get; set; }
        [Required]
        public Guid uidTicketID { get; set; }
    }

}
#pragma warning restore 1591
