// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("tblInvMenu2InvItem")]
    public partial class tblInvMenu2InvItem 
    {
        [Required]
		[PrimaryKey]
        public Guid uidInvMenu2InvItemID { get; set; }
        [Required]
        public Guid uidInvItemID { get; set; }
        [Required]
        public Guid uidInvMenuID { get; set; }
        [Required]
        public Guid uidSellableItemID { get; set; }
        [Required]
        public int lngItemOrder { get; set; }
        [Required]
        public bool blnIncreaseCoverCount { get; set; }
        [Required]
        public bool blnRepeatRound { get; set; }
        [Required]
        public Guid uidRegisterPrinterID { get; set; }
        [Required]
        public bool blnIsTemplate { get; set; }
        [Required]
        public bool blnSkipModifiers { get; set; }
        [Required]
        public Guid uidFBCourseID { get; set; }
        [Required]
        public Guid uidFB_RoomID { get; set; }
        [Required]
        public bool blnHidden { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
        [Required]
        public bool blnDeleted { get; set; }
    }

}
#pragma warning restore 1591
