// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblInvItems")]
    public partial class tblInvItem 
    {
        [Required]
		[PrimaryKey]
        public Guid uidInvItemID { get; set; }
        [Required]
        public Guid uidSellableItemID { get; set; }
        [Required]
        public string strNumber { get; set; }
        [Required]
        public Guid uidInvClassID { get; set; }
        [Required]
        public string strSellingUnit { get; set; }
        [Required]
        public string strPurchasingUnit { get; set; }
        [Required]
        public decimal lngPurchaseToSellConversion { get; set; }
        [Required]
        public decimal lngOrderPoint { get; set; }
        [Required]
        public decimal lngOrderQty { get; set; }
        [Required]
        public int lngLeadTime { get; set; }
        [Required]
        public decimal decCost { get; set; }
        [Required]
        public decimal decCostOfRecord { get; set; }
        [Required]
        public Guid uidVendorID { get; set; }
        [Required]
        public string strVendorPartNumber { get; set; }
        [Required]
        public bool blnStockItem { get; set; }
        [Required]
        public bool blnCbItem { get; set; }
        [Required]
        public decimal decTargetMargin { get; set; }
        [Required]
        public bool blnSpecialQtyItem { get; set; }
        [Required]
        public int lngSpecialQty { get; set; }
        [Required]
        public Guid uidCertCodeID { get; set; }
        [Required]
        public bool blnGiftCertItem { get; set; }
        [Required]
        public bool blnAskGuestWhenItemSold { get; set; }
        [Required]
        public bool blnIsDefaultReservableItem { get; set; }
        [Required]
        public int lngHoles { get; set; }
        [Required]
        public bool blnTeeTimeItem { get; set; }
        [Required]
        public bool blnUseTeeTimesPrice { get; set; }
        [Required]
        public string strLookupAbbreviation { get; set; }
        [Required]
        public bool blnSwipeMemberCard { get; set; }
        [Required]
        public bool blnSellableAtPOS { get; set; }
        [Required]
        public string strMenuDescription { get; set; }
        [Required]
        public int lngBackColor { get; set; }
        [Required]
        public int lngForeColor { get; set; }
        [Required]
        public Guid uidSizeGridID { get; set; }
        [Required]
        public string strExtraLineForBarCodes { get; set; }
        [Required]
        public bool blnSpecialItemOrdered { get; set; }
        [Required]
        public bool blnETS_GiftCardItem { get; set; }
        [Required]
        public bool blnFoodAndBeverageItem { get; set; }
        [Required]
        public string txtNote { get; set; }
        [Required]
        public Guid uidInvSubCategoryID { get; set; }
        [Required]
        public Guid uidImageID { get; set; }
        [Required]
        public bool blnIsTemplate { get; set; }
        [Required]
        public bool blnDeleted { get; set; }
        [Required]
        public bool blnPlayerProgramItem { get; set; }
        [Required]
        public Guid uidPlayerProgramID { get; set; }
        [Required]
        public Guid uidPlayerProgramLevelID { get; set; }
        [Required]
        public bool blnItemDetailOnStatement { get; set; }
        [Required]
        public bool blnRequiredMemUpgrade { get; set; }
        [Required]
        public Guid uidMemberTypeID { get; set; }
        [Required]
        public bool blnActivationToday { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
