// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblInvItem2InvSnapshot")]
    public partial class tblInvItem2InvSnapshot 
    {
        [Required]
		[PrimaryKey]
        public Guid uidInvItem2InvSnapshotID { get; set; }
        [Required]
        public Guid uidInvSnapshotID { get; set; }
        [Required]
        public Guid uidInvItemID { get; set; }
        [Required]
        public string strName { get; set; }
        [Required]
        public decimal decCost { get; set; }
        [Required]
        public decimal lngOnHand { get; set; }
        [Required]
        public string strNumber { get; set; }
        [Required]
        public Guid uidClassID { get; set; }
        [Required]
        public Guid uidAcctCodeID { get; set; }
        [Required]
        public Guid uidStatCodeID { get; set; }
        [Required]
        public Guid uidVendorID { get; set; }
        [Required]
        public Guid uidSizeGridID { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
        [Required]
        public int lngInvSize { get; set; }
        [Required]
        public decimal curPrice { get; set; }
        [Required]
        public bool blnStockItem { get; set; }
        [Required]
        public string strVendorPartNumber { get; set; }
    }

}
#pragma warning restore 1591
