// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblMinimums")]
    public partial class tblMinimum 
    {
        [Required]
		[PrimaryKey]
        public Guid uidMinimumID { get; set; }
        [Required]
        public Guid uidSellableItemID { get; set; }
        [Required]
        public string strMinFrequencyType { get; set; }
        [Required]
        public bool blnJanuary { get; set; }
        [Required]
        public bool blnFebruary { get; set; }
        [Required]
        public bool blnMarch { get; set; }
        [Required]
        public bool blnApril { get; set; }
        [Required]
        public bool blnMay { get; set; }
        [Required]
        public bool blnJune { get; set; }
        [Required]
        public bool blnJuly { get; set; }
        [Required]
        public bool blnAugust { get; set; }
        [Required]
        public bool blnSeptember { get; set; }
        [Required]
        public bool blnOctober { get; set; }
        [Required]
        public bool blnNovember { get; set; }
        [Required]
        public bool blnDecember { get; set; }
        [Required]
        public bool blnTerminate { get; set; }
        [Required]
        public int lngTerminatingPeriods { get; set; }
        [Required]
        public bool blnPrepaid { get; set; }
        [Required]
        public bool blnAddPrivilegeIfPrepaid { get; set; }
        [Required]
        public Guid uidPrivilegeID { get; set; }
        [Required]
        public bool blnShowRetailScreen { get; set; }
        [Required]
        public bool blnShowRetailReceipt { get; set; }
        [Required]
        public bool blnShowFB_Screen { get; set; }
        [Required]
        public bool blnShowFB_Receipt { get; set; }
        [Required]
        public bool blnDeleted { get; set; }
        [Required]
        public bool blnTrackingOnly { get; set; }
        [Required]
        public bool blnMonthsToAdvance { get; set; }
        [Required]
        public int lngMonthsToAdvance { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
