// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblMemberBalances")]
    public partial class tblMemberBalance 
    {
        [Required]
		[PrimaryKey]
        public Guid uidMemberBalanceID { get; set; }
        [Required]
        public DateTime dtmStatementPrintDate { get; set; }
        [Required]
        public Guid uidMemberID { get; set; }
        [Required]
        public bool blnPrivilegesRun { get; set; }
        [Required]
        public bool blnMinimumsRun { get; set; }
        [Required]
        public bool blnFinanceChargesRun { get; set; }
        [Required]
        public bool blnStatementPrinted { get; set; }
        [Required]
        public decimal curCurrentBalance { get; set; }
        [Required]
        public decimal cur30DayBalance { get; set; }
        [Required]
        public decimal cur60DayBalance { get; set; }
        [Required]
        public decimal cur90DayBalance { get; set; }
        [Required]
        public decimal cur120DayBalance { get; set; }
        [Required]
        public bool blnLoanPaymentsProcessed { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
        [Required]
        public bool blnStatementEmailed { get; set; }
    }

}
#pragma warning restore 1591
