// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblMember2Privilege")]
    public partial class tblMember2Privilege 
    {
        [Required]
		[PrimaryKey]
        public Guid Member2Privilege { get; set; }
        [Required]
        public Guid MemberID { get; set; }
        [Required]
        public Guid PrivilegeID { get; set; }
        [Required]
        public DateTime BeginPostingDate { get; set; }
        [Required]
        public int TotalTerminatingCharges { get; set; }
        [Required]
        public decimal VariableAmount { get; set; }
        [Required]
        public bool ManualAttached { get; set; }
    }

}
#pragma warning restore 1591
