// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblMember2Minimum")]
    public partial class tblMember2Minimum 
    {
        [Required]
		[PrimaryKey]
        public Guid uidMember2MinimumID { get; set; }
        [Required]
        public Guid uidMemberID { get; set; }
        [Required]
        public Guid uidMinimumID { get; set; }
        [Required]
        public decimal curRequiredPurchaseAmount { get; set; }
        [Required]
        public DateTime dtmDeadline { get; set; }
        [Required]
        public int lngMonthsInMinimumCycle { get; set; }
        [Required]
        public int lngCycleCount { get; set; }
        [Required]
        public Guid uidSplitMinimumID { get; set; }
        [Required]
        public decimal lngThreshold { get; set; }
        [Required]
        public bool blnAvailed { get; set; }
        [Required]
        public bool blnProRated { get; set; }
        [Required]
        public Guid uidOriginalMember2MinimumID { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
