// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblMemberTypes")]
    public partial class tblMemberType 
    {
        [Required]
		[PrimaryKey]
        public Guid uidMemberTypeID { get; set; }
        [Required]
        public string strName { get; set; }
        [Required]
        public string strNumber { get; set; }
        [Required]
        public Guid uidAcctCodeID { get; set; }
        [Required]
        public bool blnMembersCanExpire { get; set; }
        [Required]
        public Guid uidExpireMemberStatusID { get; set; }
        [Required]
        public string strExpireChangeComment { get; set; }
        [Required]
        public Guid uidExpireAwardLevelID { get; set; }
        [Required]
        public Guid uidExpireMemberTypeID { get; set; }
        [Required]
        public Guid uidExpirePlayerTypeID { get; set; }
        [Required]
        public bool blnExpireRemoveDiscClub { get; set; }
        [Required]
        public bool blnDeleted { get; set; }
        [Required]
        public bool blnExpireAROnly { get; set; }
        [Required]
        public bool blnExpireRemainingSpecPlay { get; set; }
        [Required]
        public int lngPlayDays { get; set; }
        [Required]
        public Guid uidPlayerTypeID { get; set; }
        [Required]
        public bool blnProhibitBookExp { get; set; }
        [Required]
        public Guid uidSpecialPlayerTypeID { get; set; }
        [Required]
        public bool blnSpecialPlay { get; set; }
        [Required]
        public string strExpirationModeData { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
