// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblMemberTrans")]
    public partial class tblMemberTran 
    {
        [Required]
		[PrimaryKey]
        public Guid uidMemberTranID { get; set; }
        [Required]
        public Guid uidMemberID { get; set; }
        [Required]
        public Guid uidMemberPurchaseID { get; set; }
        [Required]
        public DateTimeOffset dtmTranDate { get; set; }
        [Required]
        public Guid uidTicketID { get; set; }
        [Required]
        public string strDescription { get; set; }
        [Required]
        public decimal curTotalTranAmount { get; set; }
        [Required]
        public Guid uidMemberBalanceID { get; set; }
        [Required]
        public string strMemberTranType { get; set; }
        public string strReference { get; set; }
        public Guid? uidTicketTranID { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
