// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("tblMembers")]
    public partial class tblMember 
    {
        [Required]
		[PrimaryKey]
        public Guid uidMemberID { get; set; }
        [Required]
        public string strNumber { get; set; }
        [Required]
        public string strMemberExtension { get; set; }
        [Required]
        public Guid uidPersonID { get; set; }
        [Required]
        public Guid uidMemberTypeID { get; set; }
        [Required]
        public bool blnIsMember { get; set; }
        [Required]
        public Guid uidDiscClubID { get; set; }
        [Required]
        public bool blnTaxExempt { get; set; }
        [Required]
        public bool blnAROnly { get; set; }
        [Required]
        public Guid uidAwardLevelID { get; set; }
        [Required]
        public string strComment { get; set; }
        [Required]
        public decimal decGrat { get; set; }
        [Required]
        public bool blnMemberExpired { get; set; }
        public DateTime? dtmMemberExpirationDate { get; set; }
        public DateTime? dtmMemberActivationDate { get; set; }
        [Required]
        public bool blnLP_Participant { get; set; }
        [Required]
        public bool blnPromptForLP { get; set; }
        [Required]
        public Guid uidLP_TierID { get; set; }
        [Required]
        public bool blnIsOnMasterCb { get; set; }
        [Required]
        public bool blnIsOnMasterLP { get; set; }
        [Required]
        public bool blnPrintOnMasterStatement { get; set; }
        [Required]
        public Guid uidMasterMemberID { get; set; }
        [Required]
        public Guid uidHomeClubID { get; set; }
        public DateTime? dtmJoinedDate { get; set; }
        [Required]
        public bool blnIsTemplate { get; set; }
        [Required]
        public Guid uidPlayerTypeId { get; set; }
        [Required]
        public Guid uidCbMemberID { get; set; }
        [Required]
        public Guid uidLpMemberID { get; set; }
        [Required]
        public Guid uidBpMemberID { get; set; }
        [Required]
        public bool blnBillingIsMailingAddr { get; set; }
        [Required]
        public string txtNote { get; set; }
        [Required]
        public bool blnDeleted { get; set; }
        public bool? blnExportReceipts { get; set; }
        [Required]
        public bool blnMemberLoanParticipant { get; set; }
        [Required]
        public bool blnIsProspect { get; set; }
        [Required]
        public bool blnCampaignOptOut { get; set; }
        [Required]
        public bool blnRemoveFromTeeTimes { get; set; }
        [Required]
        public bool blnRemoveFromSpa { get; set; }
        public DateTime? dtmResignedDate { get; set; }
        [Required]
        public Guid uidMemberStatusID { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
