// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("tblPrivileges")]
    public partial class tblPrivilege 
    {
        [Required]
		[PrimaryKey]
        public Guid PrivilegeID { get; set; }
        [Required]
        public Guid SellableItemID { get; set; }
        [Required]
        public string PrivFrequencyType { get; set; }
        [Required]
        public bool January { get; set; }
        [Required]
        public bool February { get; set; }
        [Required]
        public bool March { get; set; }
        [Required]
        public bool April { get; set; }
        [Required]
        public bool May { get; set; }
        [Required]
        public bool June { get; set; }
        [Required]
        public bool July { get; set; }
        [Required]
        public bool August { get; set; }
        [Required]
        public bool September { get; set; }
        [Required]
        public bool October { get; set; }
        [Required]
        public bool November { get; set; }
        [Required]
        public bool December { get; set; }
        [Required]
        public bool VariableAmount { get; set; }
        [Required]
        public string VariableDescription { get; set; }
        [Required]
        public bool Terminating { get; set; }
        [Required]
        public int TerminatingMonths { get; set; }
        [Required]
        public bool PrintOnStatement { get; set; }
        [Required]
        public bool Deleted { get; set; }
        [Required]
        public string MemberStatementName { get; set; }
        [Required]
        public bool AllowCycleChange { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
