// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("tblRegisters")]
    public partial class tblRegister 
    {
        [Required]
		[PrimaryKey]
        public Guid uidRegisterID { get; set; }
        [Required]
        public string strMachineOrClientName { get; set; }
        [Required]
        public string strName { get; set; }
        [Required]
        public Guid uidDeptID { get; set; }
        [Required]
        public Guid uidFacilityID { get; set; }
        [Required]
        public string strDefaultModuleType { get; set; }
        [Required]
        public Guid uidFB_RoomID { get; set; }
        [Required]
        public string strCC_IdentificationNumber { get; set; }
        [Required]
        public bool blnTurnOffReceiptPrinting { get; set; }
        public bool? blnShouldPrintAdditionalReceipt { get; set; }
        [Required]
        public bool blnPOS_OnTopAfterSale { get; set; }
        [Required]
        public bool blnTerminalService { get; set; }
        [Required]
        public Guid uidRegisterPrinterID { get; set; }
        [Required]
        public string strRegLet { get; set; }
        [Required]
        public int lngInactivityLogout { get; set; }
        [Required]
        public bool blnHasDebitPIN_Pad { get; set; }
        public string strDebitIdentificationNumber { get; set; }
        [Required]
        public DateTime dtmLastKeysetDate { get; set; }
        [Required]
        public string strBarCodePrinterType { get; set; }
        public string strWindowsPrinterNameForReceipts { get; set; }
        public string strWindowsPrinterNameForReports { get; set; }
        public string strWindowsPrinterNameForBarCodeLabels { get; set; }
        [Required]
        public bool blnRegisteredLicense { get; set; }
        [Required]
        public bool blnServerBanking { get; set; }
        [Required]
        public bool blnDeleted { get; set; }
        [Required]
        public string strEmployeeBiometricScannerID { get; set; }
        [Required]
        public string strMemberBiometricScannerID { get; set; }
        [Required]
        public bool blnLockDownRegister { get; set; }
        [Required]
        public bool blnPromptForRoom { get; set; }
        [Required]
        public string CCIntegrationType { get; set; }
        [Required]
        public bool blnEncryptedSwipeAttached { get; set; }
        [Required]
        public string strCreditDebitDevice { get; set; }
        [AutoIncrement]
        public int str911PrefixNumber { get; set; }
        [Required]
        public string strTeeSheetUrl { get; set; }
        [Required]
        public string strLastTeeSheetUrl { get; set; }
        [Required]
        public bool blnEmailReceipts { get; set; }
        [Required]
        public string strPoleDisplay { get; set; }
        [Required]
        public bool blnTouchscreenSignatureCapture { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
        [Required]
        public bool blnDisableTenderCounts { get; set; }
    }

}
#pragma warning restore 1591
