// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("tblReOpenedDays")]
    public partial class tblReOpenedDay 
    {
        [Required]
		[PrimaryKey]
        public Guid uidReOpenedDayID { get; set; }
        [Required]
        public Guid uidDailyCloseID { get; set; }
        [Required]
        public string strZeesBeforeReOpen { get; set; }
        [Required]
        public Guid uidEmplID { get; set; }
        [Required]
        public DateTimeOffset dtmReOpenDateTime { get; set; }
        [Required]
        public string strComment { get; set; }
    }

}
#pragma warning restore 1591
