// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("tblZees")]
    public partial class tblZee 
    {
        [Required]
		[PrimaryKey]
        public Guid uidZeeID { get; set; }
        [Required]
        public Guid uidDailyCloseID { get; set; }
        [Required]
        public int lngZeeNumber { get; set; }
        [Required]
        public bool blnClosed { get; set; }
        [Required]
        public bool blnPending { get; set; }
        [Required]
        public Guid uidRegisterID { get; set; }
        [Required]
        public decimal curCashDeposit { get; set; }
        [Required]
        public DateTimeOffset Created { get; set; }
        [Required]
        public Guid CreatedByID { get; set; }
        [Required]
        public DateTimeOffset LastUpdated { get; set; }
        [Required]
        public Guid LastUpdatedByID { get; set; }
    }

}
#pragma warning restore 1591
