// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Default
{
	[Alias("TeeSheetTenderedBookings")]
    public partial class TeeSheetTenderedBooking 
    {
        [Required]
		[PrimaryKey]
        public Guid TeeSheetTenderedBookingID { get; set; }
        [Required]
        public Guid TicketTranID { get; set; }
        [Required]
        public Guid TicketID { get; set; }
        [Required]
        public int BookingID { get; set; }
        [Required]
        public DateTime BookingDateTime { get; set; }
        [Required]
        public DateTimeOffset TenderedDateTime { get; set; }
        [Required]
        public int FacilityID { get; set; }
        public string FacilityName { get; set; }
        [Required]
        public Guid PersonID { get; set; }
        [Required]
        public string PlayerName { get; set; }
        public string PlayerNumber { get; set; }
        [Required]
        public int PlayerTypeID { get; set; }
        [Required]
        public decimal Rate { get; set; }
        [Required]
        public int ReservationID { get; set; }
        [Required]
        public int TeeID { get; set; }
        [Required]
        public string TeeName { get; set; }
    }

}
#pragma warning restore 1591
