// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("TeeSlots")]
    public partial class TeeSlot 
    {
        [AutoIncrement]
		[PrimaryKey]
        public long Id { get; set; }
        public string Notes { get; set; }
        [Required]
        public int SlotOptions_CapacityPerSlot { get; set; }
        [Required]
        public decimal SlotOptions_IntervalMinutes { get; set; }
        [Required]
        public int SlotScheduleId { get; set; }
        [Required]
        public int TeeId { get; set; }
        [Required]
        public int Time_Hour { get; set; }
        [Required]
        public int Time_Minute { get; set; }
        [Required]
        public int Time_Second { get; set; }
        [Required]
        public DateTime Date { get; set; }
        public Guid? LockId { get; set; }
    }

}
#pragma warning restore 1591
