// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ClubData
{
	[Alias("WeeklySchedules")]
    public partial class WeeklySchedule 
    {
        [AutoIncrement]
		[PrimaryKey]
        public int Id { get; set; }
        [Required]
        public int End_Hour { get; set; }
        [Required]
        public int End_Minute { get; set; }
        [Required]
        public int End_Second { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public int Start_Hour { get; set; }
        [Required]
        public int Start_Minute { get; set; }
        [Required]
        public int Start_Second { get; set; }
        [Required]
        public bool Monday { get; set; }
        [Required]
        public bool Tuesday { get; set; }
        [Required]
        public bool Wednesday { get; set; }
        [Required]
        public bool Thursday { get; set; }
        [Required]
        public bool Friday { get; set; }
        [Required]
        public bool Saturday { get; set; }
        [Required]
        public bool Sunday { get; set; }
        public int? SeasonSchedule_Id { get; set; }
        [Required]
        public bool IsDeleted { get; set; }
    }

}
#pragma warning restore 1591
